select * 
    from table(tasty_bytes.information_schema.task_history(
    SCHEDULED_TIME_RANGE_START => DATEADD('day', -7, CURRENT_TIMESTAMP()),
    RESULT_LIMIT => 200
)) 
order by scheduled_time desc;

SHOW TASKS LIKE 'PROCESS_ORDERS_HEADER_SPROC' IN SCHEMA TASTY_BYTES.RAW_POS;

SET task_id = (SELECT "id" FROM TABLE(RESULT_SCAN(LAST_QUERY_ID())));


SELECT *
FROM TABLE(TASTY_BYTES.INFORMATION_SCHEMA.TASK_HISTORY(
    ROOT_TASK_ID => $task_id,
    RESULT_LIMIT => 10
))
ORDER BY scheduled_time;    

SELECT email FROM SNOWFLAKE.ACCOUNT_USAGE.USERS WHERE deleted_on IS NULL;

SHOW ALERTS LIKE 'DAG_COMPLETION_ALERT' IN SCHEMA TASTY_BYTES.RAW_POS;

SELECT *
FROM TABLE(SNOWFLAKE.INFORMATION_SCHEMA.ALERT_HISTORY(
    SCHEDULED_TIME_RANGE_START => DATEADD('day', -1, CURRENT_TIMESTAMP())
))
WHERE NAME = 'DAG_COMPLETION_ALERT'
ORDER BY SCHEDULED_TIME DESC;